//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddyScript.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AddyScript.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à abnormal list termination, another item was expected.
        /// </summary>
        internal static string AbnormalListTermination {
            get {
                return ResourceManager.GetString("AbnormalListTermination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An abstract member can&apos;t have a body.
        /// </summary>
        internal static string AbstractMemberCantHaveBody {
            get {
                return ResourceManager.GetString("AbstractMemberCantHaveBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A non abstract class cannot have abstract members.
        /// </summary>
        internal static string AbstractMemberInNonAbstractClass {
            get {
                return ResourceManager.GetString("AbstractMemberInNonAbstractClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cannot access to {0} from {1}.
        /// </summary>
        internal static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The scope of an accessor must be more restrictive than the property&apos;s scope.
        /// </summary>
        internal static string AccessorScopeMustBeMoreRestrictive {
            get {
                return ResourceManager.GetString("AccessorScopeMustBeMoreRestrictive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Argument {0} of &apos;{1}&apos; must be of the {2} type.
        /// </summary>
        internal static string ArgMustBeOfType {
            get {
                return ResourceManager.GetString("ArgMustBeOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The following statement does not support attributes.
        /// </summary>
        internal static string AttributesNotSupported {
            get {
                return ResourceManager.GetString("AttributesNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à date::create expects 3, 4, 6 or 7 arguments. The number or arguments ({0}) provided is invalid..
        /// </summary>
        internal static string BadDateCreateCall {
            get {
                return ResourceManager.GetString("BadDateCreateCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The given expression is not a closure.
        /// </summary>
        internal static string CalleeIsNotClosure {
            get {
                return ResourceManager.GetString("CalleeIsNotClosure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cannot access to abstract property {0}.
        /// </summary>
        internal static string CannotAccessAbstractProperty {
            get {
                return ResourceManager.GetString("CannotAccessAbstractProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cannot alter a constant object.
        /// </summary>
        internal static string CannotAlterConstant {
            get {
                return ResourceManager.GetString("CannotAlterConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cannot convert from {0} to {1}.
        /// </summary>
        internal static string CannotConvert {
            get {
                return ResourceManager.GetString("CannotConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cannot automatically handle conversions from {0}.
        /// </summary>
        internal static string CannotConvertFrom {
            get {
                return ResourceManager.GetString("CannotConvertFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cannot convert the expression to {0}.
        /// </summary>
        internal static string CannotConvertTo {
            get {
                return ResourceManager.GetString("CannotConvertTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cannot create an instance of abstract or static class {0}.
        /// </summary>
        internal static string CannotCreateInstance {
            get {
                return ResourceManager.GetString("CannotCreateInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cannot create a subclass of final or static class {0}.
        /// </summary>
        internal static string CannotCreateSubclass {
            get {
                return ResourceManager.GetString("CannotCreateSubclass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cannot invoke abstract member {0}.
        /// </summary>
        internal static string CannotInvokeAbstractMember {
            get {
                return ResourceManager.GetString("CannotInvokeAbstractMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cannot jump out of the finally block.
        /// </summary>
        internal static string CannotJumpOutOfFinallyBlock {
            get {
                return ResourceManager.GetString("CannotJumpOutOfFinallyBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cannot read a write-only property.
        /// </summary>
        internal static string CannotReadProperty {
            get {
                return ResourceManager.GetString("CannotReadProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cannot return from the finally block.
        /// </summary>
        internal static string CannotReturnFromFinallyBlock {
            get {
                return ResourceManager.GetString("CannotReturnFromFinallyBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cannot change the value of a final field.
        /// </summary>
        internal static string CannotWriteFinalField {
            get {
                return ResourceManager.GetString("CannotWriteFinalField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cannot write a read-only property.
        /// </summary>
        internal static string CannotWriteProperty {
            get {
                return ResourceManager.GetString("CannotWriteProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A switch block must contain at least one case label.
        /// </summary>
        internal static string CaseLabelRequired {
            get {
                return ResourceManager.GetString("CaseLabelRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A try statement without resource should have either a catch block or a finally block.
        /// </summary>
        internal static string CatchOrFinallyBlockRequired {
            get {
                return ResourceManager.GetString("CatchOrFinallyBlockRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The {0} type has no indexer.
        /// </summary>
        internal static string ClassHasNoIndexer {
            get {
                return ResourceManager.GetString("ClassHasNoIndexer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The {0} type has no property.
        /// </summary>
        internal static string ClassHasNoProperty {
            get {
                return ResourceManager.GetString("ClassHasNoProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A constant field should be initialized upon declaration.
        /// </summary>
        internal static string ConstantFieldShouldBeInitialized {
            get {
                return ResourceManager.GetString("ConstantFieldShouldBeInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A constructor is not allowed to return a value.
        /// </summary>
        internal static string ConstructorCantReturnValue {
            get {
                return ResourceManager.GetString("ConstructorCantReturnValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Each attribute must be unique in the list.
        /// </summary>
        internal static string DuplicatedAttribute {
            get {
                return ResourceManager.GetString("DuplicatedAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Each property must be unique in an attribute.
        /// </summary>
        internal static string DuplicatedAttributeProperty {
            get {
                return ResourceManager.GetString("DuplicatedAttributeProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Each case label must be unique in a swith block.
        /// </summary>
        internal static string DuplicatedCaseLabel {
            get {
                return ResourceManager.GetString("DuplicatedCaseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Each constant must be unique.
        /// </summary>
        internal static string DuplicatedConstant {
            get {
                return ResourceManager.GetString("DuplicatedConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Each value must be unique in a set.
        /// </summary>
        internal static string DuplicatedItem {
            get {
                return ResourceManager.GetString("DuplicatedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Each item of a map must have a unique key.
        /// </summary>
        internal static string DuplicatedKey {
            get {
                return ResourceManager.GetString("DuplicatedKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A {0} label already exists in the current scope.
        /// </summary>
        internal static string DuplicatedLabel {
            get {
                return ResourceManager.GetString("DuplicatedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Each parameter must be unique in the list.
        /// </summary>
        internal static string DuplicatedParameter {
            get {
                return ResourceManager.GetString("DuplicatedParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Each property of an object must have a unique name.
        /// </summary>
        internal static string DuplicatedProperty {
            get {
                return ResourceManager.GetString("DuplicatedProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A read accessor has already been defined for the property.
        /// </summary>
        internal static string DuplicatedReadAccessor {
            get {
                return ResourceManager.GetString("DuplicatedReadAccessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Each variable must be declared once in its scope.
        /// </summary>
        internal static string DuplicatedVariable {
            get {
                return ResourceManager.GetString("DuplicatedVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A write accessor has already been defined for the property.
        /// </summary>
        internal static string DuplicatedWriteAccessor {
            get {
                return ResourceManager.GetString("DuplicatedWriteAccessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Event {0} is already declared in ancestor {1}.
        /// </summary>
        internal static string EventDeclaredInAncestor {
            get {
                return ResourceManager.GetString("EventDeclaredInAncestor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Event {0} hides an inherited homonymous field, property or method.
        /// </summary>
        internal static string EventHidesHomonymous {
            get {
                return ResourceManager.GetString("EventHidesHomonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An expression is required.
        /// </summary>
        internal static string ExpressionRequired {
            get {
                return ResourceManager.GetString("ExpressionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à False.
        /// </summary>
        internal static string FALSE {
            get {
                return ResourceManager.GetString("FALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Field {0} is already declared in ancestor {1}.
        /// </summary>
        internal static string FieldDeclaredInAncestor {
            get {
                return ResourceManager.GetString("FieldDeclaredInAncestor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Field {0} hides an inherited homonymous property, method or event.
        /// </summary>
        internal static string FieldHidesHomonymous {
            get {
                return ResourceManager.GetString("FieldHidesHomonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} has no parameter named {1}.
        /// </summary>
        internal static string FunctionHasNoParameterNamed {
            get {
                return ResourceManager.GetString("FunctionHasNoParameterNamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Automatic accessors generation is not supported for indexers.
        /// </summary>
        internal static string IndexerCantBeAuto {
            get {
                return ResourceManager.GetString("IndexerCantBeAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An indexer cannot be static.
        /// </summary>
        internal static string IndexerCantBeStatic {
            get {
                return ResourceManager.GetString("IndexerCantBeStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à There is no item {0} in the collection.
        /// </summary>
        internal static string IndexNotFound {
            get {
                return ResourceManager.GetString("IndexNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à At least, one accessor must have the same scope than the property.
        /// </summary>
        internal static string InvalidAccessorsScope {
            get {
                return ResourceManager.GetString("InvalidAccessorsScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A constant cannot be of the {0} type. Only bool, int, long, float, decimal, complex, date and string are accepted.
        /// </summary>
        internal static string InvalidConstantType {
            get {
                return ResourceManager.GetString("InvalidConstantType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No modifier is allowed for the constructor.
        /// </summary>
        internal static string InvalidConstructorModifier {
            get {
                return ResourceManager.GetString("InvalidConstructorModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &apos;{0}&apos; is not a valid date part. Only &apos;year&apos;, &apos;month&apos;, &apos;yearday&apos;, &apos;weekday&apos;, &apos;day&apos;, &apos;hour&apos;, &apos;minute&apos;, &apos;second&apos; and &apos;millisecond&apos; are accepted..
        /// </summary>
        internal static string InvalidDatePart {
            get {
                return ResourceManager.GetString("InvalidDatePart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &apos;{0}&apos; is not a valid unit of time. Only &apos;year&apos;, &apos;month&apos;, &apos;day&apos;, &apos;hour&apos;, &apos;minute&apos;, &apos;second&apos; and &apos;millisecond&apos; are accepted..
        /// </summary>
        internal static string InvalidDateUnit {
            get {
                return ResourceManager.GetString("InvalidDateUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The given string does not contain a valid expression.
        /// </summary>
        internal static string InvalidEvalParam {
            get {
                return ResourceManager.GetString("InvalidEvalParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier &apos;{0}&apos; cannot be applied to a field.
        /// </summary>
        internal static string InvalidFieldModifier {
            get {
                return ResourceManager.GetString("InvalidFieldModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The left operand is not a valid lvalue.
        /// </summary>
        internal static string InvalidLValue {
            get {
                return ResourceManager.GetString("InvalidLValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid modifier for member {0}. Only &apos;final&apos; is allowed.
        /// </summary>
        internal static string InvalidMemberModifier {
            get {
                return ResourceManager.GetString("InvalidMemberModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid expression termination; an object initializer or a call to a constructor is expected.
        /// </summary>
        internal static string InvalidNewUsage {
            get {
                return ResourceManager.GetString("InvalidNewUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid operands count for operator {0}.
        /// </summary>
        internal static string InvalidOperandCount {
            get {
                return ResourceManager.GetString("InvalidOperandCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The left operand of &apos;with&apos; should be an object.
        /// </summary>
        internal static string InvalidOperandForWith {
            get {
                return ResourceManager.GetString("InvalidOperandForWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No modifier is allowed for an operator overloading.
        /// </summary>
        internal static string InvalidOperatorModifier {
            get {
                return ResourceManager.GetString("InvalidOperatorModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid external type reference: {0}.
        /// </summary>
        internal static string InvalidTypeReference {
            get {
                return ResourceManager.GetString("InvalidTypeReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cannot iterate through a variable of type {0}.
        /// </summary>
        internal static string IterationNotSupported {
            get {
                return ResourceManager.GetString("IterationNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An iterator cannot return any value.
        /// </summary>
        internal static string IteratorCantReturnValue {
            get {
                return ResourceManager.GetString("IteratorCantReturnValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The script is trying to jump to a case label out of a switch block.
        /// </summary>
        internal static string JumpToCaseLabelOutOfSwitchBlock {
            get {
                return ResourceManager.GetString("JumpToCaseLabelOutOfSwitchBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The list of variables can&apos;t be empty.
        /// </summary>
        internal static string ListCantBeEmpty {
            get {
                return ResourceManager.GetString("ListCantBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Both lists should have the same length.
        /// </summary>
        internal static string ListLengthMismatch {
            get {
                return ResourceManager.GetString("ListLengthMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The expression must be a literal value.
        /// </summary>
        internal static string LiteralRequired {
            get {
                return ResourceManager.GetString("LiteralRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A mandatory parameter cannot follow an optional one.
        /// </summary>
        internal static string MandatoryParamsPrecede {
            get {
                return ResourceManager.GetString("MandatoryParamsPrecede", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Member {0} cannot be overriden.
        /// </summary>
        internal static string MemberCantOverride {
            get {
                return ResourceManager.GetString("MemberCantOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Another member is declared with the name {0}.
        /// </summary>
        internal static string MemberNameConfict {
            get {
                return ResourceManager.GetString("MemberNameConfict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Method {0} hides an inherited homonymous field, property or event.
        /// </summary>
        internal static string MethodHidesHomonymous {
            get {
                return ResourceManager.GetString("MethodHidesHomonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à There is no {0} method in class {1}.
        /// </summary>
        internal static string MethodNotFound {
            get {
                return ResourceManager.GetString("MethodNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} is a method but is used as a property.
        /// </summary>
        internal static string MethodUsedAsProperty {
            get {
                return ResourceManager.GetString("MethodUsedAsProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No &apos;{0}&apos; attribute is attached to the {1} external function.
        /// </summary>
        internal static string MissingAttribute {
            get {
                return ResourceManager.GetString("MissingAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A &apos;{0}&apos; field is missing in the &apos;{1}&apos; attribute.
        /// </summary>
        internal static string MissingAttributeProperty {
            get {
                return ResourceManager.GetString("MissingAttributeProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A &apos;}&apos; is missing.
        /// </summary>
        internal static string MissingClosingBrace {
            get {
                return ResourceManager.GetString("MissingClosingBrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Missing closing parenthesis.
        /// </summary>
        internal static string MissingClosingParen {
            get {
                return ResourceManager.GetString("MissingClosingParen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Label &apos;{0}&apos; is not declared in the current scope.
        /// </summary>
        internal static string MissingLabel {
            get {
                return ResourceManager.GetString("MissingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No value was supplied for the &apos;{0}&apos; parameter of {1}.
        /// </summary>
        internal static string MissingPameter {
            get {
                return ResourceManager.GetString("MissingPameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cannot load module {0}. Check the &apos;ImportPaths&apos; property of your ScriptContext.
        /// </summary>
        internal static string ModuleNotFound {
            get {
                return ResourceManager.GetString("ModuleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} must have the same signature than {1}.
        /// </summary>
        internal static string MustMatchSignature {
            get {
                return ResourceManager.GetString("MustMatchSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} must either override {1} or be marked as abstract.
        /// </summary>
        internal static string MustOverride {
            get {
                return ResourceManager.GetString("MustOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The name {0} is already in use.
        /// </summary>
        internal static string NameConflict {
            get {
                return ResourceManager.GetString("NameConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The keyword &apos;break&apos; cannot be used out of a loop or a switch block.
        /// </summary>
        internal static string NoBreakOutOfLoop {
            get {
                return ResourceManager.GetString("NoBreakOutOfLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The keyword &apos;continue&apos; cannot be used out of a loop.
        /// </summary>
        internal static string NoContinueOutOfLoop {
            get {
                return ResourceManager.GetString("NoContinueOutOfLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Either a read accessor or a write accessor must be defined.
        /// </summary>
        internal static string NoEmptyProperty {
            get {
                return ResourceManager.GetString("NoEmptyProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No matching indexer found in {0}.
        /// </summary>
        internal static string NoMatchingIndexer {
            get {
                return ResourceManager.GetString("NoMatchingIndexer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No matching property found in {0}.
        /// </summary>
        internal static string NoMatchingProperty {
            get {
                return ResourceManager.GetString("NoMatchingProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} is not static.
        /// </summary>
        internal static string NonStaticMember {
            get {
                return ResourceManager.GetString("NonStaticMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The given expression is not a reference.
        /// </summary>
        internal static string NotAReference {
            get {
                return ResourceManager.GetString("NotAReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} is not a variable.
        /// </summary>
        internal static string NotAVariable {
            get {
                return ResourceManager.GetString("NotAVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The object&apos;s type is not enumerable.
        /// </summary>
        internal static string NotEnumerable {
            get {
                return ResourceManager.GetString("NotEnumerable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The object is in an intermediary state.
        ///It requires some initialization to support the expected operation..
        /// </summary>
        internal static string ObjectInInvalidState {
            get {
                return ResourceManager.GetString("ObjectInInvalidState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Expected: a boolean, an integer or a string value.
        /// </summary>
        internal static string OnlyBoolIntOrString {
            get {
                return ResourceManager.GetString("OnlyBoolIntOrString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Operator {0} cannot be applied to {1}.
        /// </summary>
        internal static string OperatorCantBeApplied {
            get {
                return ResourceManager.GetString("OperatorCantBeApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid format for a call to pack or unpack.
        /// </summary>
        internal static string PackInvalidFormat {
            get {
                return ResourceManager.GetString("PackInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The number of values supplied doesn&apos;t match the number of format specifiers.
        /// </summary>
        internal static string PackValuesDontMatchFormat {
            get {
                return ResourceManager.GetString("PackValuesDontMatchFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Parameter {0} of {1} is not optional.
        /// </summary>
        internal static string ParameterIsNotOptional {
            get {
                return ResourceManager.GetString("ParameterIsNotOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Several arguments are supplied for parameter {0}.
        /// </summary>
        internal static string ParameterSuppliedTwice {
            get {
                return ResourceManager.GetString("ParameterSuppliedTwice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Property {0} hides an inherited homonymous field, method or event.
        /// </summary>
        internal static string PropertyHidesHomonymous {
            get {
                return ResourceManager.GetString("PropertyHidesHomonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à There is no {0} property in class {1}.
        /// </summary>
        internal static string PropertyNotFoundInClass {
            get {
                return ResourceManager.GetString("PropertyNotFoundInClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The object has no {0} property.
        /// </summary>
        internal static string PropertyNotFoundInObject {
            get {
                return ResourceManager.GetString("PropertyNotFoundInObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} is a property but is used as a method.
        /// </summary>
        internal static string PropertyUsedAsMethod {
            get {
                return ResourceManager.GetString("PropertyUsedAsMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The script cannot return a value.
        /// </summary>
        internal static string ScriptCannotReturnValue {
            get {
                return ResourceManager.GetString("ScriptCannotReturnValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Argument {0} of &apos;{1}&apos; must be a single character.
        /// </summary>
        internal static string SingleCharExpected {
            get {
                return ResourceManager.GetString("SingleCharExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A constructor is already defined for this class.
        /// </summary>
        internal static string SingleConstructor {
            get {
                return ResourceManager.GetString("SingleConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An indexer is already defined for this class.
        /// </summary>
        internal static string SingleIndexer {
            get {
                return ResourceManager.GetString("SingleIndexer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The {0} type does not have support for slice extraction.
        /// </summary>
        internal static string SlicingNotSupported {
            get {
                return ResourceManager.GetString("SlicingNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The combination of the &apos;static&apos; and &apos;final&apos; modifiers can only be applied to a field.
        /// </summary>
        internal static string SpecificFieldModifier {
            get {
                return ResourceManager.GetString("SpecificFieldModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A statement is required.
        /// </summary>
        internal static string StatementRequired {
            get {
                return ResourceManager.GetString("StatementRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A static class cannot have a superclass. Either remove the &apos;static&apos; keyword or remove the superclass specification.
        /// </summary>
        internal static string StaticClassHasNoSuperClass {
            get {
                return ResourceManager.GetString("StaticClassHasNoSuperClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Any member of a static class must be static.
        /// </summary>
        internal static string StaticClassMember {
            get {
                return ResourceManager.GetString("StaticClassMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Strings are immutable.
        /// </summary>
        internal static string StringsAreImmutable {
            get {
                return ResourceManager.GetString("StringsAreImmutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The keyword &apos;super&apos; cannot be used out of a method&apos;s body.
        /// </summary>
        internal static string SuperUsedOutOfMethod {
            get {
                return ResourceManager.GetString("SuperUsedOutOfMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The keyword &apos;this&apos; cannot be used out of a non-static method&apos;s body.
        /// </summary>
        internal static string ThisUsedOutOfMethod {
            get {
                return ResourceManager.GetString("ThisUsedOutOfMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Too few arguments for a call to {0}.
        /// </summary>
        internal static string TooFewArgs {
            get {
                return ResourceManager.GetString("TooFewArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Too many arguments for a call to {0}.
        /// </summary>
        internal static string TooManyArgs {
            get {
                return ResourceManager.GetString("TooManyArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à True.
        /// </summary>
        internal static string TRUE {
            get {
                return ResourceManager.GetString("TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Function {0} does not accept arguments of type {1}.
        /// </summary>
        internal static string TypeDoesNotSupportFunction {
            get {
                return ResourceManager.GetString("TypeDoesNotSupportFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A type name is expected.
        /// </summary>
        internal static string TypeNameExpected {
            get {
                return ResourceManager.GetString("TypeNameExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to find the corresponding method in {0}.
        /// </summary>
        internal static string UnableToFindMethod {
            get {
                return ResourceManager.GetString("UnableToFindMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Function {0} is undefined.
        /// </summary>
        internal static string UndefinedFunction {
            get {
                return ResourceManager.GetString("UndefinedFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Could not find any symbol named {0}.
        /// </summary>
        internal static string UndefinedSymbol {
            get {
                return ResourceManager.GetString("UndefinedSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type or namespace {0} is undefined.
        /// </summary>
        internal static string UndefinedType {
            get {
                return ResourceManager.GetString("UndefinedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Variable {0} is undefined.
        /// </summary>
        internal static string UndefinedVariable {
            get {
                return ResourceManager.GetString("UndefinedVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unexpected token {0}.
        /// </summary>
        internal static string UnexpectedToken {
            get {
                return ResourceManager.GetString("UnexpectedToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Variable {0} has not been set a value.
        /// </summary>
        internal static string UninitializedVariable {
            get {
                return ResourceManager.GetString("UninitializedVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type {0} does not have a predefined order.
        /// </summary>
        internal static string UnorderedType {
            get {
                return ResourceManager.GetString("UnorderedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} is not an overloadable operator.
        /// </summary>
        internal static string UnoverloadableOperator {
            get {
                return ResourceManager.GetString("UnoverloadableOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unresolved member reference: {0}.
        /// </summary>
        internal static string UnresolvedMemberRef {
            get {
                return ResourceManager.GetString("UnresolvedMemberRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please use Parser to recognize inline functions and lambda expressions.
        /// </summary>
        internal static string UseParserForInlineFuncs {
            get {
                return ResourceManager.GetString("UseParserForInlineFuncs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A variably sized list of arguments must be the last in the function&apos;s header.
        /// </summary>
        internal static string VaArgsMustBeTheLast {
            get {
                return ResourceManager.GetString("VaArgsMustBeTheLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The value should not be empty.
        /// </summary>
        internal static string ValueShouldNotBeEmpty {
            get {
                return ResourceManager.GetString("ValueShouldNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à yield can only be used in an iterator.
        /// </summary>
        internal static string YieldUsedOutOfIterator {
            get {
                return ResourceManager.GetString("YieldUsedOutOfIterator", resourceCulture);
            }
        }
    }
}
