//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddyScript.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("AddyScript.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AbnormalListTermination {
            get {
                return ResourceManager.GetString("AbnormalListTermination", resourceCulture);
            }
        }
        
        internal static string AbstractMemberCantHaveBody {
            get {
                return ResourceManager.GetString("AbstractMemberCantHaveBody", resourceCulture);
            }
        }
        
        internal static string AbstractMemberInNonAbstractClass {
            get {
                return ResourceManager.GetString("AbstractMemberInNonAbstractClass", resourceCulture);
            }
        }
        
        internal static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        internal static string AccessorScopeMustBeMoreRestrictive {
            get {
                return ResourceManager.GetString("AccessorScopeMustBeMoreRestrictive", resourceCulture);
            }
        }
        
        internal static string ArgMustBeOfType {
            get {
                return ResourceManager.GetString("ArgMustBeOfType", resourceCulture);
            }
        }
        
        internal static string AttributesNotSupported {
            get {
                return ResourceManager.GetString("AttributesNotSupported", resourceCulture);
            }
        }
        
        internal static string BadDateOfCall {
            get {
                return ResourceManager.GetString("BadDateOfCall", resourceCulture);
            }
        }
        
        internal static string BothAccessorsCantRedefineScope {
            get {
                return ResourceManager.GetString("BothAccessorsCantRedefineScope", resourceCulture);
            }
        }
        
        internal static string CalleeIsNotClosure {
            get {
                return ResourceManager.GetString("CalleeIsNotClosure", resourceCulture);
            }
        }
        
        internal static string CannotAccessAbstractProperty {
            get {
                return ResourceManager.GetString("CannotAccessAbstractProperty", resourceCulture);
            }
        }
        
        internal static string CannotAlterConstant {
            get {
                return ResourceManager.GetString("CannotAlterConstant", resourceCulture);
            }
        }
        
        internal static string CannotComputeGcdForNegative {
            get {
                return ResourceManager.GetString("CannotComputeGcdForNegative", resourceCulture);
            }
        }
        
        internal static string CannotConvert {
            get {
                return ResourceManager.GetString("CannotConvert", resourceCulture);
            }
        }
        
        internal static string CannotConvertFrom {
            get {
                return ResourceManager.GetString("CannotConvertFrom", resourceCulture);
            }
        }
        
        internal static string CannotConvertTo {
            get {
                return ResourceManager.GetString("CannotConvertTo", resourceCulture);
            }
        }
        
        internal static string CannotCreateEmptyTuple {
            get {
                return ResourceManager.GetString("CannotCreateEmptyTuple", resourceCulture);
            }
        }
        
        internal static string CannotCreateInstance {
            get {
                return ResourceManager.GetString("CannotCreateInstance", resourceCulture);
            }
        }
        
        internal static string CannotCreateSubclass {
            get {
                return ResourceManager.GetString("CannotCreateSubclass", resourceCulture);
            }
        }
        
        internal static string CannotInvokeAbstractMember {
            get {
                return ResourceManager.GetString("CannotInvokeAbstractMember", resourceCulture);
            }
        }
        
        internal static string CannotJumpOutOfFinallyBlock {
            get {
                return ResourceManager.GetString("CannotJumpOutOfFinallyBlock", resourceCulture);
            }
        }
        
        internal static string CannotReadProperty {
            get {
                return ResourceManager.GetString("CannotReadProperty", resourceCulture);
            }
        }
        
        internal static string CannotReturnFromFinallyBlock {
            get {
                return ResourceManager.GetString("CannotReturnFromFinallyBlock", resourceCulture);
            }
        }
        
        internal static string CannotWriteFinalField {
            get {
                return ResourceManager.GetString("CannotWriteFinalField", resourceCulture);
            }
        }
        
        internal static string CannotWriteProperty {
            get {
                return ResourceManager.GetString("CannotWriteProperty", resourceCulture);
            }
        }
        
        internal static string CaseLabelRequired {
            get {
                return ResourceManager.GetString("CaseLabelRequired", resourceCulture);
            }
        }
        
        internal static string CatchOrFinallyBlockRequired {
            get {
                return ResourceManager.GetString("CatchOrFinallyBlockRequired", resourceCulture);
            }
        }
        
        internal static string ClassHasNoIndexReader {
            get {
                return ResourceManager.GetString("ClassHasNoIndexReader", resourceCulture);
            }
        }
        
        internal static string ClassHasNoIndexWriter {
            get {
                return ResourceManager.GetString("ClassHasNoIndexWriter", resourceCulture);
            }
        }
        
        internal static string ClassHasNoProperty {
            get {
                return ResourceManager.GetString("ClassHasNoProperty", resourceCulture);
            }
        }
        
        internal static string ClassHasNoRangeReader {
            get {
                return ResourceManager.GetString("ClassHasNoRangeReader", resourceCulture);
            }
        }
        
        internal static string ClassHasNoRangeWriter {
            get {
                return ResourceManager.GetString("ClassHasNoRangeWriter", resourceCulture);
            }
        }
        
        internal static string ConstantFieldShouldBeInitialized {
            get {
                return ResourceManager.GetString("ConstantFieldShouldBeInitialized", resourceCulture);
            }
        }
        
        internal static string ConstructorCantReturnValue {
            get {
                return ResourceManager.GetString("ConstructorCantReturnValue", resourceCulture);
            }
        }
        
        internal static string DuplicatedAttribute {
            get {
                return ResourceManager.GetString("DuplicatedAttribute", resourceCulture);
            }
        }
        
        internal static string DuplicatedAttributeField {
            get {
                return ResourceManager.GetString("DuplicatedAttributeField", resourceCulture);
            }
        }
        
        internal static string DuplicatedAttributeValue {
            get {
                return ResourceManager.GetString("DuplicatedAttributeValue", resourceCulture);
            }
        }
        
        internal static string DuplicatedCaseLabel {
            get {
                return ResourceManager.GetString("DuplicatedCaseLabel", resourceCulture);
            }
        }
        
        internal static string DuplicatedConstant {
            get {
                return ResourceManager.GetString("DuplicatedConstant", resourceCulture);
            }
        }
        
        internal static string DuplicatedItem {
            get {
                return ResourceManager.GetString("DuplicatedItem", resourceCulture);
            }
        }
        
        internal static string DuplicatedKey {
            get {
                return ResourceManager.GetString("DuplicatedKey", resourceCulture);
            }
        }
        
        internal static string DuplicatedLabel {
            get {
                return ResourceManager.GetString("DuplicatedLabel", resourceCulture);
            }
        }
        
        internal static string DuplicatedParameter {
            get {
                return ResourceManager.GetString("DuplicatedParameter", resourceCulture);
            }
        }
        
        internal static string DuplicatedProperty {
            get {
                return ResourceManager.GetString("DuplicatedProperty", resourceCulture);
            }
        }
        
        internal static string DuplicatedVariable {
            get {
                return ResourceManager.GetString("DuplicatedVariable", resourceCulture);
            }
        }
        
        internal static string EventDeclaredInAncestor {
            get {
                return ResourceManager.GetString("EventDeclaredInAncestor", resourceCulture);
            }
        }
        
        internal static string EventHidesHomonymous {
            get {
                return ResourceManager.GetString("EventHidesHomonymous", resourceCulture);
            }
        }
        
        internal static string ExpressionRequired {
            get {
                return ResourceManager.GetString("ExpressionRequired", resourceCulture);
            }
        }
        
        internal static string FieldDeclaredInAncestor {
            get {
                return ResourceManager.GetString("FieldDeclaredInAncestor", resourceCulture);
            }
        }
        
        internal static string FieldHidesHomonymous {
            get {
                return ResourceManager.GetString("FieldHidesHomonymous", resourceCulture);
            }
        }
        
        internal static string FunctionHasNoParameterNamed {
            get {
                return ResourceManager.GetString("FunctionHasNoParameterNamed", resourceCulture);
            }
        }
        
        internal static string IndexerCantBeAuto {
            get {
                return ResourceManager.GetString("IndexerCantBeAuto", resourceCulture);
            }
        }
        
        internal static string IndexerCantBeStatic {
            get {
                return ResourceManager.GetString("IndexerCantBeStatic", resourceCulture);
            }
        }
        
        internal static string IndexNotFound {
            get {
                return ResourceManager.GetString("IndexNotFound", resourceCulture);
            }
        }
        
        internal static string InvalidAccessorsScope {
            get {
                return ResourceManager.GetString("InvalidAccessorsScope", resourceCulture);
            }
        }
        
        internal static string InvalidConstantType {
            get {
                return ResourceManager.GetString("InvalidConstantType", resourceCulture);
            }
        }
        
        internal static string InvalidConstructorModifier {
            get {
                return ResourceManager.GetString("InvalidConstructorModifier", resourceCulture);
            }
        }
        
        internal static string InvalidDatePart {
            get {
                return ResourceManager.GetString("InvalidDatePart", resourceCulture);
            }
        }
        
        internal static string InvalidDateUnit {
            get {
                return ResourceManager.GetString("InvalidDateUnit", resourceCulture);
            }
        }
        
        internal static string InvalidEvalParam {
            get {
                return ResourceManager.GetString("InvalidEvalParam", resourceCulture);
            }
        }
        
        internal static string InvalidFieldModifier {
            get {
                return ResourceManager.GetString("InvalidFieldModifier", resourceCulture);
            }
        }
        
        internal static string InvalidLValue {
            get {
                return ResourceManager.GetString("InvalidLValue", resourceCulture);
            }
        }
        
        internal static string InvalidMemberModifier {
            get {
                return ResourceManager.GetString("InvalidMemberModifier", resourceCulture);
            }
        }
        
        internal static string InvalidNewUsage {
            get {
                return ResourceManager.GetString("InvalidNewUsage", resourceCulture);
            }
        }
        
        internal static string InvalidOperandCount {
            get {
                return ResourceManager.GetString("InvalidOperandCount", resourceCulture);
            }
        }
        
        internal static string InvalidOperandForWith {
            get {
                return ResourceManager.GetString("InvalidOperandForWith", resourceCulture);
            }
        }
        
        internal static string InvalidOperatorModifier {
            get {
                return ResourceManager.GetString("InvalidOperatorModifier", resourceCulture);
            }
        }
        
        internal static string InvalidTypeReference {
            get {
                return ResourceManager.GetString("InvalidTypeReference", resourceCulture);
            }
        }
        
        internal static string IterationNotSupported {
            get {
                return ResourceManager.GetString("IterationNotSupported", resourceCulture);
            }
        }
        
        internal static string IteratorCantReturnValue {
            get {
                return ResourceManager.GetString("IteratorCantReturnValue", resourceCulture);
            }
        }
        
        internal static string JumpToCaseLabelOutOfSwitchBlock {
            get {
                return ResourceManager.GetString("JumpToCaseLabelOutOfSwitchBlock", resourceCulture);
            }
        }
        
        internal static string ListCantBeEmpty {
            get {
                return ResourceManager.GetString("ListCantBeEmpty", resourceCulture);
            }
        }
        
        internal static string ListLengthMismatch {
            get {
                return ResourceManager.GetString("ListLengthMismatch", resourceCulture);
            }
        }
        
        internal static string LiteralRequired {
            get {
                return ResourceManager.GetString("LiteralRequired", resourceCulture);
            }
        }
        
        internal static string MandatoryParamsPrecede {
            get {
                return ResourceManager.GetString("MandatoryParamsPrecede", resourceCulture);
            }
        }
        
        internal static string MemberCantOverride {
            get {
                return ResourceManager.GetString("MemberCantOverride", resourceCulture);
            }
        }
        
        internal static string MemberNameConfict {
            get {
                return ResourceManager.GetString("MemberNameConfict", resourceCulture);
            }
        }
        
        internal static string MethodHidesHomonymous {
            get {
                return ResourceManager.GetString("MethodHidesHomonymous", resourceCulture);
            }
        }
        
        internal static string MethodNotFound {
            get {
                return ResourceManager.GetString("MethodNotFound", resourceCulture);
            }
        }
        
        internal static string MethodUsedAsProperty {
            get {
                return ResourceManager.GetString("MethodUsedAsProperty", resourceCulture);
            }
        }
        
        internal static string MissingAttribute {
            get {
                return ResourceManager.GetString("MissingAttribute", resourceCulture);
            }
        }
        
        internal static string MissingAttributeProperty {
            get {
                return ResourceManager.GetString("MissingAttributeProperty", resourceCulture);
            }
        }
        
        internal static string MissingClosingBrace {
            get {
                return ResourceManager.GetString("MissingClosingBrace", resourceCulture);
            }
        }
        
        internal static string MissingClosingParen {
            get {
                return ResourceManager.GetString("MissingClosingParen", resourceCulture);
            }
        }
        
        internal static string MissingLabel {
            get {
                return ResourceManager.GetString("MissingLabel", resourceCulture);
            }
        }
        
        internal static string MissingPameter {
            get {
                return ResourceManager.GetString("MissingPameter", resourceCulture);
            }
        }
        
        internal static string ModuleNotFound {
            get {
                return ResourceManager.GetString("ModuleNotFound", resourceCulture);
            }
        }
        
        internal static string MustMatchSignature {
            get {
                return ResourceManager.GetString("MustMatchSignature", resourceCulture);
            }
        }
        
        internal static string MustOverride {
            get {
                return ResourceManager.GetString("MustOverride", resourceCulture);
            }
        }
        
        internal static string NameConflict {
            get {
                return ResourceManager.GetString("NameConflict", resourceCulture);
            }
        }
        
        internal static string NoBreakOutOfLoop {
            get {
                return ResourceManager.GetString("NoBreakOutOfLoop", resourceCulture);
            }
        }
        
        internal static string NoContinueOutOfLoop {
            get {
                return ResourceManager.GetString("NoContinueOutOfLoop", resourceCulture);
            }
        }
        
        internal static string NoEmptyProperty {
            get {
                return ResourceManager.GetString("NoEmptyProperty", resourceCulture);
            }
        }
        
        internal static string NoMatchingIndexer {
            get {
                return ResourceManager.GetString("NoMatchingIndexer", resourceCulture);
            }
        }
        
        internal static string NoMatchingProperty {
            get {
                return ResourceManager.GetString("NoMatchingProperty", resourceCulture);
            }
        }
        
        internal static string NonStaticMember {
            get {
                return ResourceManager.GetString("NonStaticMember", resourceCulture);
            }
        }
        
        internal static string NotAReference {
            get {
                return ResourceManager.GetString("NotAReference", resourceCulture);
            }
        }
        
        internal static string NotAVariable {
            get {
                return ResourceManager.GetString("NotAVariable", resourceCulture);
            }
        }
        
        internal static string NotEnumerable {
            get {
                return ResourceManager.GetString("NotEnumerable", resourceCulture);
            }
        }
        
        internal static string ObjectInInvalidState {
            get {
                return ResourceManager.GetString("ObjectInInvalidState", resourceCulture);
            }
        }
        
        internal static string OnlyBoolIntOrString {
            get {
                return ResourceManager.GetString("OnlyBoolIntOrString", resourceCulture);
            }
        }
        
        internal static string OperatorCantBeApplied {
            get {
                return ResourceManager.GetString("OperatorCantBeApplied", resourceCulture);
            }
        }
        
        internal static string PackInvalidFormat {
            get {
                return ResourceManager.GetString("PackInvalidFormat", resourceCulture);
            }
        }
        
        internal static string PackValuesDontMatchFormat {
            get {
                return ResourceManager.GetString("PackValuesDontMatchFormat", resourceCulture);
            }
        }
        
        internal static string ParameterIsNotOptional {
            get {
                return ResourceManager.GetString("ParameterIsNotOptional", resourceCulture);
            }
        }
        
        internal static string ParameterNameExpected {
            get {
                return ResourceManager.GetString("ParameterNameExpected", resourceCulture);
            }
        }
        
        internal static string ParameterSuppliedTwice {
            get {
                return ResourceManager.GetString("ParameterSuppliedTwice", resourceCulture);
            }
        }
        
        internal static string PropertyHidesHomonymous {
            get {
                return ResourceManager.GetString("PropertyHidesHomonymous", resourceCulture);
            }
        }
        
        internal static string PropertyNotFoundInClass {
            get {
                return ResourceManager.GetString("PropertyNotFoundInClass", resourceCulture);
            }
        }
        
        internal static string PropertyNotFoundInObject {
            get {
                return ResourceManager.GetString("PropertyNotFoundInObject", resourceCulture);
            }
        }
        
        internal static string PropertyUsedAsMethod {
            get {
                return ResourceManager.GetString("PropertyUsedAsMethod", resourceCulture);
            }
        }
        
        internal static string ScriptCannotReturnValue {
            get {
                return ResourceManager.GetString("ScriptCannotReturnValue", resourceCulture);
            }
        }
        
        internal static string SingleCharExpected {
            get {
                return ResourceManager.GetString("SingleCharExpected", resourceCulture);
            }
        }
        
        internal static string SingleConstructor {
            get {
                return ResourceManager.GetString("SingleConstructor", resourceCulture);
            }
        }
        
        internal static string SingleIndexer {
            get {
                return ResourceManager.GetString("SingleIndexer", resourceCulture);
            }
        }
        
        internal static string SlicingNotSupported {
            get {
                return ResourceManager.GetString("SlicingNotSupported", resourceCulture);
            }
        }
        
        internal static string SpecificFieldModifier {
            get {
                return ResourceManager.GetString("SpecificFieldModifier", resourceCulture);
            }
        }
        
        internal static string StatementRequired {
            get {
                return ResourceManager.GetString("StatementRequired", resourceCulture);
            }
        }
        
        internal static string StaticClassHasNoSuperClass {
            get {
                return ResourceManager.GetString("StaticClassHasNoSuperClass", resourceCulture);
            }
        }
        
        internal static string StaticClassMember {
            get {
                return ResourceManager.GetString("StaticClassMember", resourceCulture);
            }
        }
        
        internal static string StringsAreImmutable {
            get {
                return ResourceManager.GetString("StringsAreImmutable", resourceCulture);
            }
        }
        
        internal static string SuperUsedOutOfMethod {
            get {
                return ResourceManager.GetString("SuperUsedOutOfMethod", resourceCulture);
            }
        }
        
        internal static string ThisUsedOutOfMethod {
            get {
                return ResourceManager.GetString("ThisUsedOutOfMethod", resourceCulture);
            }
        }
        
        internal static string TooFewArgs {
            get {
                return ResourceManager.GetString("TooFewArgs", resourceCulture);
            }
        }
        
        internal static string TooManyArgs {
            get {
                return ResourceManager.GetString("TooManyArgs", resourceCulture);
            }
        }
        
        internal static string TuplesAreImmutable {
            get {
                return ResourceManager.GetString("TuplesAreImmutable", resourceCulture);
            }
        }
        
        internal static string TypeDoesNotSupportFunction {
            get {
                return ResourceManager.GetString("TypeDoesNotSupportFunction", resourceCulture);
            }
        }
        
        internal static string TypeNameExpected {
            get {
                return ResourceManager.GetString("TypeNameExpected", resourceCulture);
            }
        }
        
        internal static string UnableToFindMethod {
            get {
                return ResourceManager.GetString("UnableToFindMethod", resourceCulture);
            }
        }
        
        internal static string UndefinedFunction {
            get {
                return ResourceManager.GetString("UndefinedFunction", resourceCulture);
            }
        }
        
        internal static string UndefinedSymbol {
            get {
                return ResourceManager.GetString("UndefinedSymbol", resourceCulture);
            }
        }
        
        internal static string UndefinedType {
            get {
                return ResourceManager.GetString("UndefinedType", resourceCulture);
            }
        }
        
        internal static string UndefinedVariable {
            get {
                return ResourceManager.GetString("UndefinedVariable", resourceCulture);
            }
        }
        
        internal static string UnexpectedToken {
            get {
                return ResourceManager.GetString("UnexpectedToken", resourceCulture);
            }
        }
        
        internal static string UninitializedVariable {
            get {
                return ResourceManager.GetString("UninitializedVariable", resourceCulture);
            }
        }
        
        internal static string UnorderedType {
            get {
                return ResourceManager.GetString("UnorderedType", resourceCulture);
            }
        }
        
        internal static string UnoverloadableOperator {
            get {
                return ResourceManager.GetString("UnoverloadableOperator", resourceCulture);
            }
        }
        
        internal static string UnresolvedMemberRef {
            get {
                return ResourceManager.GetString("UnresolvedMemberRef", resourceCulture);
            }
        }
        
        internal static string UseParserForInlineFuncs {
            get {
                return ResourceManager.GetString("UseParserForInlineFuncs", resourceCulture);
            }
        }
        
        internal static string VaArgsMustBeTheLast {
            get {
                return ResourceManager.GetString("VaArgsMustBeTheLast", resourceCulture);
            }
        }
        
        internal static string ValueShouldNotBeEmpty {
            get {
                return ResourceManager.GetString("ValueShouldNotBeEmpty", resourceCulture);
            }
        }
        
        internal static string YieldUsedOutOfIterator {
            get {
                return ResourceManager.GetString("YieldUsedOutOfIterator", resourceCulture);
            }
        }
        
        internal static string EmptyPatternGroup {
            get {
                return ResourceManager.GetString("EmptyPatternGroup", resourceCulture);
            }
        }
    }
}
