//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddyScript.Gui.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AddyScript.Gui.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Could not load assembly {0}.
        /// </summary>
        internal static string AssemblyLoadFailureMessage {
            get {
                return ResourceManager.GetString("AssemblyLoadFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid assembly&apos;s name.
        /// </summary>
        internal static string AssemblyLoadFailureTitle {
            get {
                return ResourceManager.GetString("AssemblyLoadFailureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CAPS.
        /// </summary>
        internal static string CapsLoc {
            get {
                return ResourceManager.GetString("CapsLoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ln {0}   Col {1}   Sel {2}.
        /// </summary>
        internal static string CaretStatus {
            get {
                return ResourceManager.GetString("CaretStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à , .
        /// </summary>
        internal static string Comma {
            get {
                return ResourceManager.GetString("Comma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you really want to delete this item?.
        /// </summary>
        internal static string ConfirmationBoxMessage {
            get {
                return ResourceManager.GetString("ConfirmationBoxMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmation needed.
        /// </summary>
        internal static string ConfirmationBoxTitle {
            get {
                return ResourceManager.GetString("ConfirmationBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Something went wrong.
        /// </summary>
        internal static string ErrorMessageBody {
            get {
                return ResourceManager.GetString("ErrorMessageBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error.
        /// </summary>
        internal static string ErrorMessageTitle {
            get {
                return ResourceManager.GetString("ErrorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export the script to.
        /// </summary>
        internal static string ExportXmlTitle {
            get {
                return ResourceManager.GetString("ExportXmlTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File: .
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à AddyScript files (*.add; *.txt)|*.add; *.txt|All files (*.*)|*.*.
        /// </summary>
        internal static string FileDialogFilter {
            get {
                return ResourceManager.GetString("FileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Initialization failure.
        /// </summary>
        internal static string InitializationFailure {
            get {
                return ResourceManager.GetString("InitializationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OVR.
        /// </summary>
        internal static string InsLoc {
            get {
                return ResourceManager.GetString("InsLoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à INS.
        /// </summary>
        internal static string InsUnloc {
            get {
                return ResourceManager.GetString("InsUnloc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Line: .
        /// </summary>
        internal static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Missing functionality.
        /// </summary>
        internal static string MissingFunctionality {
            get {
                return ResourceManager.GetString("MissingFunctionality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New script.
        /// </summary>
        internal static string NewScript {
            get {
                return ResourceManager.GetString("NewScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Not yet implemented.
        /// </summary>
        internal static string NotImplemented {
            get {
                return ResourceManager.GetString("NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à NUM.
        /// </summary>
        internal static string NumLoc {
            get {
                return ResourceManager.GetString("NumLoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open a script.
        /// </summary>
        internal static string OpenFileDialogTitle {
            get {
                return ResourceManager.GetString("OpenFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Press any key to return....
        /// </summary>
        internal static string PressAnyKeyToReturn {
            get {
                return ResourceManager.GetString("PressAnyKeyToReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save changes to the current script?.
        /// </summary>
        internal static string PromptToSave {
            get {
                return ResourceManager.GetString("PromptToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save the script as.
        /// </summary>
        internal static string SaveFileDialogTitle {
            get {
                return ResourceManager.GetString("SaveFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The {0} type does not have support for slice extraction.
        /// </summary>
        internal static string SlicingNotSupported {
            get {
                return ResourceManager.GetString("SlicingNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} characters.
        /// </summary>
        internal static string TextLength {
            get {
                return ResourceManager.GetString("TextLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Xml file (*.xml)|*.xml|All files (*.*)|*.*.
        /// </summary>
        internal static string XmlFileFilter {
            get {
                return ResourceManager.GetString("XmlFileFilter", resourceCulture);
            }
        }
    }
}
