//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddyScript.Gui.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("AddyScript.Gui.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AssemblyLoadFailureMessage {
            get {
                return ResourceManager.GetString("AssemblyLoadFailureMessage", resourceCulture);
            }
        }
        
        internal static string AssemblyLoadFailureTitle {
            get {
                return ResourceManager.GetString("AssemblyLoadFailureTitle", resourceCulture);
            }
        }
        
        internal static string CapsLoc {
            get {
                return ResourceManager.GetString("CapsLoc", resourceCulture);
            }
        }
        
        internal static string CaretStatus {
            get {
                return ResourceManager.GetString("CaretStatus", resourceCulture);
            }
        }
        
        internal static string Comma {
            get {
                return ResourceManager.GetString("Comma", resourceCulture);
            }
        }
        
        internal static string ConfirmationBoxMessage {
            get {
                return ResourceManager.GetString("ConfirmationBoxMessage", resourceCulture);
            }
        }
        
        internal static string ConfirmationBoxTitle {
            get {
                return ResourceManager.GetString("ConfirmationBoxTitle", resourceCulture);
            }
        }
        
        internal static string ErrorMessageBody {
            get {
                return ResourceManager.GetString("ErrorMessageBody", resourceCulture);
            }
        }
        
        internal static string ErrorMessageTitle {
            get {
                return ResourceManager.GetString("ErrorMessageTitle", resourceCulture);
            }
        }
        
        internal static string ExportXmlTitle {
            get {
                return ResourceManager.GetString("ExportXmlTitle", resourceCulture);
            }
        }
        
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        internal static string FileDialogFilter {
            get {
                return ResourceManager.GetString("FileDialogFilter", resourceCulture);
            }
        }
        
        internal static string InitializationFailure {
            get {
                return ResourceManager.GetString("InitializationFailure", resourceCulture);
            }
        }
        
        internal static string InsLoc {
            get {
                return ResourceManager.GetString("InsLoc", resourceCulture);
            }
        }
        
        internal static string InsUnloc {
            get {
                return ResourceManager.GetString("InsUnloc", resourceCulture);
            }
        }
        
        internal static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        internal static string MissingFunctionality {
            get {
                return ResourceManager.GetString("MissingFunctionality", resourceCulture);
            }
        }
        
        internal static string NewScript {
            get {
                return ResourceManager.GetString("NewScript", resourceCulture);
            }
        }
        
        internal static string NotImplemented {
            get {
                return ResourceManager.GetString("NotImplemented", resourceCulture);
            }
        }
        
        internal static string NumLoc {
            get {
                return ResourceManager.GetString("NumLoc", resourceCulture);
            }
        }
        
        internal static string OpenFileDialogTitle {
            get {
                return ResourceManager.GetString("OpenFileDialogTitle", resourceCulture);
            }
        }
        
        internal static string PressAnyKeyToReturn {
            get {
                return ResourceManager.GetString("PressAnyKeyToReturn", resourceCulture);
            }
        }
        
        internal static string PromptToSave {
            get {
                return ResourceManager.GetString("PromptToSave", resourceCulture);
            }
        }
        
        internal static string SaveFileDialogTitle {
            get {
                return ResourceManager.GetString("SaveFileDialogTitle", resourceCulture);
            }
        }
        
        internal static string TextLength {
            get {
                return ResourceManager.GetString("TextLength", resourceCulture);
            }
        }
        
        internal static string XmlFileFilter {
            get {
                return ResourceManager.GetString("XmlFileFilter", resourceCulture);
            }
        }
        
        internal static string SlicingNotSupported {
            get {
                return ResourceManager.GetString("SlicingNotSupported", resourceCulture);
            }
        }
        
        internal static string AboutBoxTitle {
            get {
                return ResourceManager.GetString("AboutBoxTitle", resourceCulture);
            }
        }
        
        internal static string VersionLabel {
            get {
                return ResourceManager.GetString("VersionLabel", resourceCulture);
            }
        }
        
        internal static string DirectoryNotFound {
            get {
                return ResourceManager.GetString("DirectoryNotFound", resourceCulture);
            }
        }
        
        internal static string DirectoryChooserTitle {
            get {
                return ResourceManager.GetString("DirectoryChooserTitle", resourceCulture);
            }
        }
        
        internal static string AssemblyChooserTitle {
            get {
                return ResourceManager.GetString("AssemblyChooserTitle", resourceCulture);
            }
        }
        
        internal static string AssemblyChooserFilter {
            get {
                return ResourceManager.GetString("AssemblyChooserFilter", resourceCulture);
            }
        }
        
        internal static string OptionDialogTitle {
            get {
                return ResourceManager.GetString("OptionDialogTitle", resourceCulture);
            }
        }
    }
}
